name: Benchmark Main

on:
  push:
    branches:
      - main
    paths:
      - "packages/cachebay/**"
      - "packages/benchmarks/**"

jobs:
  benchmark:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: pnpm/action-setup@v4
        with:
          version: 9

      - uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "pnpm"

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Install Playwright
        run: pnpm --filter benchmarks exec playwright install chromium

      - name: Run DOM benchmarks
        run: pnpm --filter benchmarks bench:ci:baseline:dom

      - name: Run API benchmarks
        run: pnpm --filter benchmarks bench:ci:baseline:api

      - name: Commit baseline results
        run: |
          VERSION=$(node -p "require('./packages/cachebay/package.json').version")
          git config user.name "LockVoid /dev/null"
          git config user.email "dev@lockvoid.com"
          git add packages/benchmarks/.bench-results/*-baseline.json packages/benchmarks/.bench-results/api-baseline.txt
          git diff --staged --quiet || git commit -m "benchmark $VERSION"
          git push

      - name: Comment on commit
        uses: actions/github-script@v7
        with:
          script: |
            const fs = require('fs');
            const apiBaseline = fs.readFileSync('packages/benchmarks/.bench-results/api-baseline.txt', 'utf8');

            github.rest.repos.createCommitComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              commit_sha: context.sha,
              body: `## 📊 Benchmark Baseline Saved\n\n### API Benchmarks\n\`\`\`\n${apiBaseline.slice(0, 2000)}\n\`\`\``
            });
